trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      TimeoutInMinutes: 240
      MaxParallel: 7
      ServiceDirectory: keyvault
      Artifacts:
        - name: azure-security-test-keyvault-jca
          groupId: com.azure
          safeName: azuresecuritytestkeyvaultjca
      EnvVars:
        ARM_CLIENTID: $(aad-azure-sdk-test-client-id)
        ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_KEYVAULT_ENDPOINT: $(AZURE_KEYVAULT_ENDPOINT)
